"""Gera fixtures de mordida determinísticos para o Beta.

Cada fixture é gravado em fixtures/<sha256_short>/ com:
- audio.wav (ou .yaml/.json para casos não-áudio)
- expected.json (decision, failed_analyzers, fixture_sha256)

Adendo S2: fixtures são imutáveis — o hash do conteúdo faz parte do path.
"""
from __future__ import annotations

import hashlib
import json
import os
import shutil
from pathlib import Path

import numpy as np
import scipy.io.wavfile as wavfile
import yaml

FIXTURES_ROOT = Path("fixtures")
SAMPLE_RATE = 48000


def _write_wav(path: Path, pcm: np.ndarray, sr: int = SAMPLE_RATE) -> None:
    """Escreve PCM float32 como WAV int16 (compatível amplo)."""
    if pcm.dtype != np.float32:
        pcm = pcm.astype(np.float32)
    # Clipa para [-1, 1] antes de converter
    pcm = np.clip(pcm, -1.0, 1.0)
    pcm_i16 = (pcm * 32767).astype(np.int16)
    if pcm_i16.ndim == 1:
        pcm_i16 = pcm_i16.reshape(-1, 1)
    path.parent.mkdir(parents=True, exist_ok=True)
    wavfile.write(str(path), sr, pcm_i16)


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_fixture(name: str, content_fn, expected: dict, ext: str = "wav") -> None:
    """Cria um fixture em fixtures/<name>/ com hash do conteúdo."""
    fixture_dir = FIXTURES_ROOT / name
    if fixture_dir.exists():
        shutil.rmtree(fixture_dir)
    fixture_dir.mkdir(parents=True)

    file_path = fixture_dir / f"audio.{ext}"
    content_fn(file_path)

    file_sha = _hash_file(file_path)
    expected_data = {
        "fixture_name": name,
        "fixture_sha256": file_sha,
        "expected_decision": expected["decision"],
        "expected_failed_analyzers": expected.get("failed_analyzers", []),
        "expected_findings": expected.get("findings", []),
        "license": "synthetic — generated by audio-suite scripts (no third-party audio)",
        "generator": "scripts/generate_fixtures.py",
    }
    (fixture_dir / "expected.json").write_text(
        json.dumps(expected_data, indent=2), encoding="utf-8"
    )


# ---------------------------------------------------------------------------
# Geradores
# ---------------------------------------------------------------------------

def _gen_clean(duration_s: float = 3.0, sr: int = SAMPLE_RATE) -> np.ndarray:
    """Senoide limpa que passa em todos os critérios."""
    frames = int(duration_s * sr)
    t = np.linspace(0, duration_s, frames, endpoint=False)
    # Amplitude ~0.1 → ~-20 dBFS → próximo de -23 LUFS
    left = 0.1 * np.sin(2 * np.pi * 440 * t)
    right = 0.1 * np.sin(2 * np.pi * 440 * t + np.pi / 6)
    return np.stack([left, right], axis=1).astype(np.float32)


def _gen_clipped(duration_s: float = 3.0, sr: int = SAMPLE_RATE) -> np.ndarray:
    """Senoide saturada — clipping intencional."""
    frames = int(duration_s * sr)
    t = np.linspace(0, duration_s, frames, endpoint=False)
    left = 1.3 * np.sin(2 * np.pi * 440 * t)
    right = 1.3 * np.sin(2 * np.pi * 440 * t + np.pi / 4)
    pcm = np.stack([left, right], axis=1).astype(np.float32)
    return np.clip(pcm, -1.0, 1.0)


def _gen_true_peak_over(duration_s: float = 3.0, sr: int = SAMPLE_RATE) -> np.ndarray:
    """Combinação de senoides para gerar true peak > -1 dBTP."""
    frames = int(duration_s * sr)
    t = np.linspace(0, duration_s, frames, endpoint=False)
    sig = 0.6 * np.sin(2 * np.pi * 440 * t)
    sig += 0.4 * np.sin(2 * np.pi * 880 * t + np.pi / 3)
    sig += 0.15 * np.sin(2 * np.pi * 1760 * t + np.pi / 2)
    sig = sig / np.max(np.abs(sig)) * 0.95  # perto de 0 dBFS
    return np.stack([sig, sig * 0.95], axis=1).astype(np.float32)


def _gen_lufs_hot(duration_s: float = 3.0, sr: int = SAMPLE_RATE) -> np.ndarray:
    """Senoide alta amplitude → LUFS acima do target."""
    frames = int(duration_s * sr)
    t = np.linspace(0, duration_s, frames, endpoint=False)
    left = 0.6 * np.sin(2 * np.pi * 440 * t)
    right = 0.6 * np.sin(2 * np.pi * 440 * t + np.pi / 6)
    return np.stack([left, right], axis=1).astype(np.float32)


def _gen_inverted_polarity(duration_s: float = 3.0, sr: int = SAMPLE_RATE) -> np.ndarray:
    """Estéreo com canal direito invertido."""
    frames = int(duration_s * sr)
    t = np.linspace(0, duration_s, frames, endpoint=False)
    left = 0.2 * np.sin(2 * np.pi * 440 * t)
    right = -left  # polaridade invertida
    return np.stack([left, right], axis=1).astype(np.float32)


def _gen_mono(duration_s: float = 3.0, sr: int = SAMPLE_RATE) -> np.ndarray:
    """Mono — para profile que requer estéreo."""
    frames = int(duration_s * sr)
    t = np.linspace(0, duration_s, frames, endpoint=False)
    sig = 0.1 * np.sin(2 * np.pi * 440 * t)
    return sig.reshape(-1, 1).astype(np.float32)


def _gen_silence(duration_s: float = 5.0, sr: int = SAMPLE_RATE) -> np.ndarray:
    """Silêncio de 5 segundos."""
    frames = int(duration_s * sr)
    return np.zeros((frames, 2), dtype=np.float32)


def _gen_with_email_tag(tmp_path: Path) -> Path:
    """WAV com tag de email (PII). Usa mutagen para gravar tag."""
    import tempfile
    pcm = _gen_clean()
    _write_wav(tmp_path, pcm)
    # Tenta gravar tag via mutagen
    try:
        from mutagen.wave import WAVE  # type: ignore
        w = WAVE(str(tmp_path))
        w.tags = {"CONTACT": "user@example.com", "ARTIST": "test"}
        w.save()
    except Exception:
        # Fallback: escreve um arquivo YAML como 'tags' lado a lado
        sidecar = tmp_path.with_suffix(".tags.yaml")
        sidecar.write_text("CONTACT: user@example.com\nARTIST: test\n")
    return tmp_path


# ---------------------------------------------------------------------------
# Fixtures não-áudio (rights, provenance)
# ---------------------------------------------------------------------------

RIGHTS_NC_COMMERCIAL = """\
project:
  name: "Campanha comercial usando asset NC"
  purpose: commercial_campaign
  territory: BR
  language: pt-BR

assets_used:
  - asset_id: "freesound:999"
    title: "Sample NC"
    licensor: "user@freesound.org"
    license: "CC-BY-NC-4.0"
    commercial_use_allowed: false
    attribution_required: true
    attribution_text: "Sample NC by user (CC-BY-NC 4.0)"
"""

PROVENANCE_GAP = {
    "events": [
        {
            "event_type": "decode_canonical",
            "input_sha256": "a" * 64,
            "output_sha256": "b" * 64,
            "decoder": "ffmpeg",
            "timestamp": 1234567890
        },
        {
            "event_type": "normalize",
            "input_sha256": "c" * 64,  # gap: não corresponde a "b"
            "output_sha256": "d" * 64,
            "decoder": "ffmpeg",
            "timestamp": 1234567891
        }
    ]
}


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

FIXTURES = [
    {
        "name": "clean_pass",
        "generator": lambda p: _write_wav(p, _gen_clean()),
        "ext": "wav",
        "expected": {
            "decision": "pass",
            "failed_analyzers": [],
            "findings": ["loudness:pass", "signal:pass"],
        },
    },
    {
        "name": "clipped_sine",
        "generator": lambda p: _write_wav(p, _gen_clipped()),
        "ext": "wav",
        "expected": {
            "decision": "fail",
            "failed_analyzers": ["signal"],
            "findings": ["signal:fail:clipping"],
        },
    },
    {
        "name": "true_peak_over",
        "generator": lambda p: _write_wav(p, _gen_true_peak_over()),
        "ext": "wav",
        "expected": {
            "decision": "fail",
            "failed_analyzers": ["signal"],
            "findings": ["signal:fail:true_peak"],
        },
    },
    {
        "name": "lufs_too_hot",
        "generator": lambda p: _write_wav(p, _gen_lufs_hot()),
        "ext": "wav",
        "expected": {
            "decision": "fail",
            "failed_analyzers": ["loudness"],
            "findings": ["loudness:fail"],
        },
    },
    {
        "name": "inverted_polarity",
        "generator": lambda p: _write_wav(p, _gen_inverted_polarity()),
        "ext": "wav",
        "expected": {
            "decision": "warning",  # phase é warning por profile
            "failed_analyzers": ["phase"],
            "findings": ["phase:fail:correlation"],
        },
    },
    {
        "name": "mono_when_stereo_req",
        "generator": lambda p: _write_wav(p, _gen_mono()),
        "ext": "wav",
        "expected": {
            "decision": "pass",  # broadcast profile não exige estéreo explicitamente
            "failed_analyzers": [],
            "findings": ["phase:not_applicable"],
        },
    },
    {
        "name": "metadata_with_email",
        "generator": _gen_with_email_tag,
        "ext": "wav",
        "expected": {
            "decision": "fail",
            "failed_analyzers": ["metadata"],
            "findings": ["metadata:fail:pii"],
        },
    },
    {
        "name": "silence_5s",
        "generator": lambda p: _write_wav(p, _gen_silence()),
        "ext": "wav",
        "expected": {
            "decision": "indeterminate",
            "failed_analyzers": [],
            "findings": ["loudness:indeterminate", "phase:not_applicable"],
        },
    },
    {
        "name": "rights_nc_commercial",
        "generator": lambda p: p.write_text(RIGHTS_NC_COMMERCIAL, encoding="utf-8"),
        "ext": "yaml",
        "expected": {
            "decision": "fail",
            "failed_analyzers": ["rights_manifest"],
            "findings": ["rights_manifest:fail:commercial_use"],
        },
    },
    {
        "name": "provenance_gap",
        "generator": lambda p: p.write_text(
            json.dumps(PROVENANCE_GAP, indent=2), encoding="utf-8"
        ),
        "ext": "json",
        "expected": {
            "decision": "indeterminate",
            "failed_analyzers": ["provenance"],
            "findings": ["provenance:needs_review:gap"],
        },
    },
]


def main() -> None:
    if FIXTURES_ROOT.exists():
        # Não apaga — fixtures devem ser imutáveis. Apenas reescreve.
        pass
    FIXTURES_ROOT.mkdir(parents=True, exist_ok=True)

    print(f"Gerando {len(FIXTURES)} fixtures em {FIXTURES_ROOT}/")
    for fx in FIXTURES:
        try:
            _write_fixture(fx["name"], fx["generator"], fx["expected"], ext=fx["ext"])
            print(f"  ✓ {fx['name']} (ext={fx['ext']})")
        except Exception as e:
            print(f"  ❌ {fx['name']}: {e}")

    # Escreve índice
    index = {
        "version": "1.0.0",
        "fixtures": [fx["name"] for fx in FIXTURES],
        "license": "All fixtures are synthetic (script-generated); no third-party audio.",
    }
    (FIXTURES_ROOT / "index.json").write_text(
        json.dumps(index, indent=2), encoding="utf-8"
    )
    print(f"\n✅ {len(FIXTURES)} fixtures gerados. Index: {FIXTURES_ROOT / 'index.json'}")


if __name__ == "__main__":
    main()
